version: '2'

services:
  frameio:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7200:80"

  framelog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6200:80"

  frameauth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5200:80"